[package]
name = "apt-alt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ar = "0.9.0"
reqwest = { version = "0.12.3", features = ["blocking"] }
select = "0.6.0"
tar = "0.4.40"
